development:
  adapter: mysql2
  encoding: utf8
  database: library_development
  username: root
  password: 
  host: localhost
  
test:
  adapter: mysql2
  database: library_test
  username: root
  password: 
  host: localhost
  
production:
  adapter: mysql2
  database: library_production
  username: root
  password: 
  host: localhost




# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)



